# 100 exercicios

**Aluno: João Soares**

**1 -**

In [1]:
import numpy as np

**2 - **

In [18]:
a = np.version.version
b = np.show_config()
a

blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/ProgramData/An

'1.12.1'

**3 - **

In [20]:
z = np.zeros(10)
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

**4 - **

In [34]:
z.size*z.itemsize

80

**5 - **

In [22]:
np.info

<function numpy.lib.utils.info>

** 6 - **

In [23]:
z[4] = 1
z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

**7 - **

In [26]:
x = np.arange(10,50,1)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8 - **

In [35]:
y = x[::-1]
y

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**9 - **

In [40]:
f = np.arange(9).reshape((3,3))
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10 - **

In [43]:
g = [1,2,0,0,4,0]
np.nonzero(g)


(array([0, 1, 4], dtype=int64),)

**11 - **

In [45]:
j = np.eye(3)
j

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

** 12 -**

In [51]:
m = np.random.random((3,3,3))
m

array([[[ 0.55999078,  0.16042484,  0.4286161 ],
        [ 0.58714235,  0.2530734 ,  0.07867388],
        [ 0.52958231,  0.32983898,  0.15064523]],

       [[ 0.747539  ,  0.66559535,  0.09195819],
        [ 0.37552556,  0.14404195,  0.03441474],
        [ 0.06160368,  0.80336946,  0.86336281]],

       [[ 0.52178043,  0.20453784,  0.29930524],
        [ 0.17342845,  0.86138573,  0.58431387],
        [ 0.53689692,  0.10537676,  0.30514743]]])

** 13 - **


In [63]:
arr = np.random.random((10,10))
arr
np.amin(arr)
np.amax(arr)

0.98899506672060478

** 14 - **

In [67]:
vec = np.random.random(30)
vec
np.mean(vec)


0.53697961266529859

** 15 - **



In [81]:
a = np.zeros(25).reshape(5,5) 
a[0] = a[:,0] = a[-1] = a[:,-1] = np.ones(())
a

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

** 16 - **

In [85]:
np.pad(a,[(1, )], mode = 'constant')

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

** 17 - **


In [88]:
0 * np.nan

nan

In [91]:
np.nan == np.nan


False

In [92]:
np.inf > np.nan


False

In [93]:
np.nan - np.nan


nan

In [94]:
np.nan in set([np.nan])


True

In [95]:
0.3 == 3 * 0.1

False

** 18 - **


In [99]:
eva = np.arange(25).reshape((5,5))
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

 ** 19 - **
 

In [116]:
a=np.array(([1,0]*4+[0,1]*4)*4).reshape((8,8))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

** 20 - **


In [133]:
np.unravel_index(100, (6,7,8))


(1, 5, 4)

** 21 - **


In [138]:
check = np.arange(64).reshape((8,8))
np.tile(check,2)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63, 56, 57, 58, 59, 60, 61, 62, 63]])

** 22 - **

In [140]:
norm = np.random.random((5,5))
norm = (norm - np.mean(norm))/ (np.std(norm))
norm

array([[ 1.07503733, -0.60286642,  1.10711704,  1.73359199, -0.87086174],
       [-0.21702649, -1.29775511,  1.69386687,  0.27949791,  0.43584272],
       [ 1.63694792, -1.36564879,  0.13075852, -1.40796893, -1.23700932],
       [ 0.54918771,  0.7316756 , -1.06044135, -0.53197768, -0.33040756],
       [-0.28983202, -0.34255548,  0.01891921,  1.30163633, -1.13972828]])

**23 - **

In [15]:
import numpy as np
np.dtype([('r', np.uint), ('g', np.uint), ('b', np.uint), ('a', np.uint)])


dtype([('r', '<u4'), ('g', '<u4'), ('b', '<u4'), ('a', '<u4')])

** 24 - **

In [17]:
x = np.random.rand(5,3)
y = np.random.rand(3,2)
print("{}\n".format(a))
print("{}\n".format(b))
print("Produto entre a matriz x e y")
print(np.dot(a, b))

[[ 0.62894593  0.13566818  0.07959608]
 [ 0.35723187  0.81223909  0.75603421]
 [ 0.37946834  0.34406048  0.56144812]
 [ 0.70078346  0.52718347  0.792745  ]
 [ 0.09586347  0.24349953  0.21868537]]

[[ 0.07665078  0.49129172]
 [ 0.43829416  0.03338591]
 [ 0.03894076  0.85655544]]

Produto entre a matriz x e y
[[ 0.1107713   0.38170379]
 [ 0.4128223   0.85020762]
 [ 0.20174946  0.67882788]
 [ 0.31564713  1.04091966]
 [ 0.12258821  0.24254253]]


** 25 - **

In [20]:
vec = np.arange(30)
np.random.shuffle(vec)
for i in range(len(vec)):
    if 3 <= vec[i] <= 8:
        vec[i] = -vec[i]
vec

array([16, 22, -6, 25, -8, 15,  0,  1, 13, 27, -3, -5, 28, 20, 29, 24,  9,
       26,  2, -4, 19, 23, 14, 17, 21, 10, 12, 11, 18, -7])

** 26 - **

In [22]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


** 27 - **

Toda as sentenças abaixo são legais!

In [23]:
Z = 10
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

False

** 28 - **

In [28]:
np.array(0) / np.array(0) 
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


C:\Users\joaos\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
C:\Users\joaos\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  from ipykernel import kernelapp as app


array([ -2.14748365e+09])

 Para o 1º resultado: NaN 
 
 Para o 2º resultado: divide by zero encountered in floor_divide
 
 Para o 3º resultado: array([ -2.14748365e+09])

** 29 - **

In [32]:
vetorUm = np.random.uniform(-10, 10, 100)
vetorDois = np.round(vetorUm + np.copysign(0.5, vetorUm))
vetorUm
vetorDois

array([  2.,   7.,  10.,  -1.,   6.,   1.,   5.,  10.,  -1.,  -1.,  10.,
         5.,   5.,  -6.,  10.,   4.,   3.,   2.,  -5.,  10.,  -3.,   1.,
        -4.,  -5.,   9.,  -9.,   1.,   5.,  -5.,   9.,  10.,   2.,   7.,
         4.,   4.,   4.,   5.,  -1.,   7.,   8.,   4.,   7.,   7.,  -4.,
         8.,   9.,   6.,  -6.,   3.,   3.,   2.,  -6.,   7.,   6.,   5.,
         9.,  -4.,   6.,   7.,   8.,   7.,  -5.,   4.,   4.,  -4.,  10.,
        -5.,   5.,  -8.,   6.,  -6.,  10.,  10.,  -3.,  -3.,  -4.,  -7.,
        -9.,  -9.,  -7.,   2.,   6.,   2.,   5.,   5.,   6.,  -3.,  -5.,
        -3.,   7.,   1.,  -2.,  -7.,   2.,   4.,   1.,  -3.,  -3.,  -1.,
         1.])

** 30 - **

In [35]:
a = np.random.randint(-10,10, 100)
b = np.random.randint(-10,10, 100)
c = np.intersect1d(a, b)
a
b
c


array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

** 31 - **

In [38]:

old_settings = np.seterr(all='ignore') 
old_settings


{'divide': 'ignore', 'invalid': 'ignore', 'over': 'ignore', 'under': 'ignore'}

** 32 - **

In [39]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

** 33 - **

In [47]:
dataHoje = np.datetime64("today")
dataOntem = dataHoje- np.timedelta64(1)
dataAmanha = dataHoje + np.timedelta64(1)
print("dataHoje: {}".format(dataHoje))
print("dataOntem: {}".format(dataOntem))
print("dataAmanha: {}".format(dataAmanha))

dataHoje: 2019-03-10
dataOntem: 2019-03-09
dataAmanha: 2019-03-11


**34 - **

In [48]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

** 35 _ **

In [50]:
x = np.random.uniform(-2, 2, 2)
y = np.random.uniform(-2, 2, 2)
print(x)
print(y)
np.add(x, y, out=y)
np.negative(x, out=x)
np.multiply(x, 0.5, out=x) 
np.multiply(x, y, out=x)
x

[ 1.42924732  0.30645685]
[ 0.96592611 -0.12740734]


array([-1.7116476 , -0.02743547])

** 36 - **

In [51]:
a = np.random.uniform(-5, 5, 10)
a
a - a % 1
np.floor(a)
np.ceil(a) - 1
a.astype(int).astype(float)
np.trunc(a)

array([-2.,  1., -1., -2., -4., -3.,  2., -2.,  3., -1.])

** 37-**

In [52]:
vector = np.zeros((5,5))
vector += np.arange(5)
vector

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

** 38 - **

In [53]:
n = 10
m = (n * np.random.rand() for x in range(n))
np.fromiter(m, float)

array([ 3.61070974,  5.4894722 ,  0.26314942,  2.63712398,  0.01090239,
        0.81253901,  9.32404294,  9.43900137,  8.70066969,  8.71850427])

** 39 - **

In [54]:
a = np.random.uniform(0, 1, 10) 
a = np.linspace(0, 1, 11, endpoint=False)[1:]
a

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

** 40 - **


In [57]:
a = np.random.randint(-5, 5, 10)
np.sort(a)

array([-5, -4, -3, -2, -2, -1,  0,  1,  2,  3])

** 41- **

In [59]:
a = np.random.randint(-20, 10, 5)
somaA = np.add.reduce(a)
a
somaA

-45

**42 - **

In [63]:
x = np.random.randint(0, 2, 4)
y = np.random.randint(0, 2, 4)
resultadoX = np.allclose(x, y) 
resultadoY = np.array_equal(x, y) 
print(x)
print(y)
print(result1)
print(result2)

[0 0 0 0]
[0 0 0 0]
False
False


** 43 - **

In [64]:
v = np.random.randint(0, 10, 10)
v.flags.writeable = False
v

array([6, 9, 9, 0, 1, 3, 8, 1, 3, 3])

** 44 - **

In [68]:
vec = np.random.randint(0, 10, 20).reshape(10,2)
x = vec[:,0]
y = vec[:,1]
z = np.sqrt(x ** 2 + y ** 2) 
arc = np.arctan2(y, x) * 180 / np.pi 
vec
np.column_stack((z, arc))

array([[  1.        ,  90.        ],
       [ 10.81665383,  56.30993247],
       [  2.82842712,  45.        ],
       [  7.07106781,   8.13010235],
       [  2.23606798,  26.56505118],
       [  2.23606798,  26.56505118],
       [ 10.63014581,  48.81407483],
       [  7.28010989,  15.9453959 ],
       [ 10.63014581,  48.81407483],
       [  3.16227766,  18.43494882]])

**45 - **

In [70]:
arr = np.random.uniform(-10, 10, 10)

arr[np.argmax(arr)] = 0
print(arr)


[ 0.          0.73402521 -3.28572723 -6.38851774 -4.01772127  3.95468458
 -0.85467602  4.49662977  0.94651827 -1.93263148]


** 46- **

In [71]:
x = np.zeros((5,5), [("x", float), ("y", float)])
x["x"], x["y"] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(x)

[[(0.0, 0.0) (0.25, 0.0) (0.5, 0.0) (0.75, 0.0) (1.0, 0.0)]
 [(0.0, 0.25) (0.25, 0.25) (0.5, 0.25) (0.75, 0.25) (1.0, 0.25)]
 [(0.0, 0.5) (0.25, 0.5) (0.5, 0.5) (0.75, 0.5) (1.0, 0.5)]
 [(0.0, 0.75) (0.25, 0.75) (0.5, 0.75) (0.75, 0.75) (1.0, 0.75)]
 [(0.0, 1.0) (0.25, 1.0) (0.5, 1.0) (0.75, 1.0) (1.0, 1.0)]]


** 47 - **

In [72]:
x = np.random.uniform(-5, 5, 5)
y = np.random.uniform(-5, 5, 5)
z = 1.0 / np.subtract.outer(x, y)
z

array([[-0.23209742,  0.59362796,  0.4121276 ,  0.39876953,  0.39473945],
       [ 3.44365491,  0.15914744,  0.1423415 ,  0.14071349,  0.14020838],
       [-0.65418   ,  0.2239912 ,  0.19207361,  0.18912106,  0.18820975],
       [ 3.69668545,  0.15965247,  0.14274537,  0.14110816,  0.14060021],
       [-0.67462878,  0.22169038,  0.1903793 ,  0.18747821,  0.18658263]])

** 48 - **

In [77]:
for dtype in [np.uint8, np.int8, np.uint16, np.int16, np.uint32, np.int32, np.uint64, np.int64]:
    dtype
    np.iinfo(dtype).min
    np.iinfo(dtype).max
    
for dtype in [np.float16, np.float32, np.float64, np.float128]:
    dtype
    np.finfo(dtype).min
    np.finfo(dtype).max
    np.finfo(dtype).eps


AttributeError: module 'numpy' has no attribute 'float128'

** 49 - **

In [79]:
np.set_printoptions(threshold=np.nan)
vec = np.arange(30)
print(vec)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


** 50 - **

In [81]:
vec = np.arange(20) 
vecEscalar = np.random.uniform(0, 20) 
vec
vecEscalar
arr[(np.abs(vec - vecEscalar)).argmin()]

3

** 51- **

In [84]:
x = [ ("posicao", [("x", float, 1),("y", float, 1)]),("cor", [("r", float, 1),("g", float, 1),
("b", float, 1)])]
np.zeros(1, x)

array([((0.0, 0.0), (0.0, 0.0, 0.0))], 
      dtype=[('posicao', [('x', '<f8'), ('y', '<f8')]), ('cor', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

** 52- **

In [89]:
vec = np.random.randint(-5, 5, (100,2))
a = np.atleast_2d(arr[:,0], arr[:,1])
b = np.atleast_2d(arr[:,0], arr[:,1])
c = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2) 
print(vec)
print(c)

IndexError: too many indices for array

** 53-**

In [92]:
vec = np.random.uniform(-2, 2, 1)
vec
arr.astype(int, copy=False)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

**54 - **

**55-**

In [12]:
vec = np.random.randint(-10, 10, 9).reshape(3,3)
vec
print("\nUtilizando np.ndenumerate:")
for i,v in np.ndenumerate(vec):
    print(i, v)
print("\nUtilizando np.ndindex:")
for i in np.ndindex(vec.shape):
    print(i, vec[i])


Utilizando np.ndenumerate:
(0, 0) 5
(0, 1) -8
(0, 2) 7
(1, 0) 1
(1, 1) 1
(1, 2) -5
(2, 0) 1
(2, 1) 2
(2, 2) 8

Utilizando np.ndindex:
(0, 0) 5
(0, 1) -8
(0, 2) 7
(1, 0) 1
(1, 1) 1
(1, 2) -5
(2, 0) 1
(2, 1) 2
(2, 2) 8


**56-**

In [16]:
x = np.meshgrid(np.linspace(-1, 1, 10))
y = np.linspace(-1, 1, 10)
z = np.sqrt(x ** 2 + y ** 2)
sigma = 1.0
mu = 0.0
gaussiana = np.exp(-((distance - mu) ** 2 / (2.0 * sigma ** 2)))
print(gaussian)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

**57-**

In [19]:
a = 10
p = 3
vec = np.zeros((a,a))
np.put(vec, np.random.choice(range(a ** 2), p, replace=False), 1)
vec

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

**58-**

In [25]:
vec = np.random.randint(-5, 5, (5,10))
vec2 = vec - vec.mean(axis=1, keepdims=True)
vec

for i in vec:
    print(i.mean())
    print(vec2)

0.3
[[ 0.7  0.7 -2.3  0.7  0.7  1.7 -4.3  3.7 -4.3  2.7]
 [ 3.1  1.1 -1.9 -4.9  2.1 -0.9 -0.9 -1.9  2.1  2.1]
 [-0.5 -3.5  1.5  3.5 -1.5  1.5  3.5 -4.5  2.5 -2.5]
 [-2.4 -2.4  1.6  1.6 -1.4 -2.4  4.6 -3.4  5.6 -1.4]
 [ 3.7  0.7 -5.3 -0.3 -1.3  1.7  3.7  2.7 -5.3 -0.3]]
0.9
[[ 0.7  0.7 -2.3  0.7  0.7  1.7 -4.3  3.7 -4.3  2.7]
 [ 3.1  1.1 -1.9 -4.9  2.1 -0.9 -0.9 -1.9  2.1  2.1]
 [-0.5 -3.5  1.5  3.5 -1.5  1.5  3.5 -4.5  2.5 -2.5]
 [-2.4 -2.4  1.6  1.6 -1.4 -2.4  4.6 -3.4  5.6 -1.4]
 [ 3.7  0.7 -5.3 -0.3 -1.3  1.7  3.7  2.7 -5.3 -0.3]]
0.5
[[ 0.7  0.7 -2.3  0.7  0.7  1.7 -4.3  3.7 -4.3  2.7]
 [ 3.1  1.1 -1.9 -4.9  2.1 -0.9 -0.9 -1.9  2.1  2.1]
 [-0.5 -3.5  1.5  3.5 -1.5  1.5  3.5 -4.5  2.5 -2.5]
 [-2.4 -2.4  1.6  1.6 -1.4 -2.4  4.6 -3.4  5.6 -1.4]
 [ 3.7  0.7 -5.3 -0.3 -1.3  1.7  3.7  2.7 -5.3 -0.3]]
-1.6
[[ 0.7  0.7 -2.3  0.7  0.7  1.7 -4.3  3.7 -4.3  2.7]
 [ 3.1  1.1 -1.9 -4.9  2.1 -0.9 -0.9 -1.9  2.1  2.1]
 [-0.5 -3.5  1.5  3.5 -1.5  1.5  3.5 -4.5  2.5 -2.5]
 [-2.4 -2.4  1.6  1.6 -1.4

**59-**

In [27]:
vec = np.random.randint(0, 9, (3,3))
vec
vec[vec[:,1].argsort()]

array([[1, 0, 0],
       [4, 8, 0],
       [0, 8, 0]])

**60-**

In [28]:
vec = np.random.randint(-3, 3, (3,10))
print(vec)
print((~vec.any(axis=0)).any())

[[ 2 -2  0  1 -3 -1 -2  0 -3  0]
 [ 2 -2  2 -2  0  0  1 -3  1 -2]
 [ 2 -1 -3  2  1 -3  2  1 -3 -3]]
False


**61-**

In [30]:
vec = np.random.rand(25)
valor = 0.5
temp = vec.flat[np.abs(vec - valor).argmin()]
print(vec)
print(temp)

[ 0.78754551  0.92894126  0.09240504  0.76496104  0.22229541  0.77798084
  0.47085456  0.91601904  0.01429962  0.86146402  0.07243959  0.89943216
  0.93396685  0.03516786  0.79406802  0.26907846  0.26290157  0.41826371
  0.15579962  0.42403194  0.04427481  0.76037736  0.31043015  0.83487419
  0.44291051]
0.470854560873


**62-**

**63-**

**64-**

In [40]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[ 2.  1.  3.  3.  3.  5.  3.  3.  4.  3.]


**65-**

In [45]:
vecA = [1,2,3,4,5,6]
vecB = [1,3,3,8,4,2]
vecC = np.bincount(vecA,vecB)
print(vecC)

[ 0.  1.  3.  3.  8.  4.  2.]


**66-**

**67-**

In [48]:
arr = np.random.randint(0,10,(3,4,3,4))
somaEixo = arr.reshape(arr.shape[:-2] + (-1,)).sum(axis=-1)
print(somaEixo)

[[39 60 40 55]
 [54 61 52 60]
 [63 44 62 52]]


**68-**

In [53]:
arr1 = np.random.uniform(-2,2,100)
arr2 = np.random.randint(0,15,100)
arr1Soma = np.bincount(arr2, weights=arr1)
arr1Cont = np.bincount(arr2)
x = arr1Soma / arr1Cont
print(x)

[ 0.24611375  0.02955222  0.35046382 -0.3216255  -0.21991459  0.28372061
  0.53994666 -0.03235126  0.36723845  0.00516683  0.01304747  0.22312984
  0.13276823  0.54336198  0.03551307]


**69-**

In [57]:
x = np.random.uniform(0,1,(5,5))
y = np.random.uniform(0,1,(5,5))
np.diag(np.dot(x, y))


array([ 0.57327783,  1.0910037 ,  1.07578756,  0.44577539,  1.87535048])

**70-**

In [59]:

x = np.array([1,2,3,4,5])
y = 3
intercalador = np.zeros(len(x) + (len(x)-1)*(y))
intercalador[::y+1] = x
intercalador

array([ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
        0.,  0.,  0.,  5.])

**72-**

In [60]:

x = np.arange(9).reshape(3,3)
x[[0,1]] = x[[1,0]]
x

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

**73-**

**74-**

In [62]:
x = np.bincount([1,1,2,3,4,4,6])
y = np.repeat(np.arange(len(x)), x)
y

array([1, 1, 2, 3, 4, 4, 6])

**75-**

**76-**

In [71]:
 from numpy.lib import stride_tricks
def deslocaLinha(a, b):
    shape = (a.size - b + 1, b)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = deslocaLinha(np.arange(20), 4)
Z

array([[ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14],
       [12, 13, 14, 15],
       [13, 14, 15, 16],
       [14, 15, 16, 17],
       [15, 16, 17, 18],
       [16, 17, 18, 19]])

**77-**

In [76]:
a = np.random.randint(0,2,100)
np.logical_not(a, out=a)
a = np.random.uniform(-5.0,1.0,100)
np.negative(a, out=a)

array([ -9.05978360e-01,  -3.60779880e-01,   1.06972087e+00,
        -9.78693367e-01,   2.94144125e+00,  -3.45248218e-01,
         4.22813020e-01,   9.15062491e-01,   3.02677568e+00,
         1.42439783e-01,   2.84261846e+00,   1.88263019e+00,
         4.83933779e+00,   1.91296577e+00,   2.46281012e+00,
         1.52785211e+00,   4.61905569e+00,   2.21547898e+00,
        -4.64771124e-01,   3.38655466e-03,  -6.03159931e-01,
         2.34548016e+00,   4.26366494e+00,  -2.14952937e-01,
         4.10773874e+00,   4.36963630e+00,   3.16032234e+00,
        -4.97709325e-01,  -3.26861267e-03,   3.54342029e+00,
         4.35375229e+00,   4.50696575e+00,   2.52689837e+00,
        -9.30134719e-01,   6.08544122e-01,  -7.68024864e-02,
         3.51441767e-01,   3.06241143e+00,   1.82894586e+00,
         2.55272373e+00,   2.61887643e+00,  -1.76942065e-02,
        -3.87148428e-01,   2.45037103e+00,   2.87703923e+00,
         3.73408964e+00,   1.12112726e+00,   1.57023950e+00,
        -7.71348522e-01,

**78-**

**79-**

**80-**

**81-**

In [81]:
vec = np.arange(1,15,dtype=np.uint32)
vec2 = stride_tricks.as_strided(vec,(11,4),(4,4))
vec2

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

**82-**

In [83]:
x = np.random.uniform(0,1,(10,10))
a, b, c = np.linalg.svd(x) 
calc = np.sum(b > 1e-10)
calc

10

**83-**

In [85]:
a = np.random.randint(0,30,50)
np.bincount(a).argmax()

4